package edu.tamu.srl.sketch.core.object;

/**
 * Created by gigemjt on 11/3/14.
 * @author gigemjt
 * @copyright Tracy Hammond, Sketch Recognition Lab, Texas A&M University
 *
 * Text can be either handwritten or defined from a keyboard.
 * If text is handwritten it will contain the shapes that make up the text.
 * If the text is defined from a keyboard it may still contains shapes inside of it.
 *
 * The text may contain unicode characters of any language.
 * And must be treated as containing unicode characters.
 */
public class SrlText extends SrlShape {

    /**
     * The discreet set of characters that is contained within this object.
     *
     * This value may contain unicode characters of any language.
     */
    private String mTextValue;

    /**
     * True if the text was generated by sketching.
     * False otherwise.
     *
     * If this object is a combination of multiple text objects then this will be true if any of them were handwritten.
     */
    private boolean mIsHandWritten;
}
